name: 1st workflow
on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
  Unit Test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Python script
        run: python Scripts/tests/tests.py